default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["AMAZING_LIST_HOST"] %>
  database: amazing_list_development
  username: amazing_list
  password: <%= ENV["AMAZING_LIST_DATABASE_PASSWORD"] %>

test:
  <<: *default
  host: <%= ENV["AMAZING_LIST_HOST"] %>
  database: amazing_list_test
  username: amazing_list
  password: <%= ENV["AMAZING_LIST_DATABASE_PASSWORD"] %>

production:
  <<: *default
  host: <%= ENV["AMAZING_LIST_HOST"] %>
  database: amazing_list_production
  username: amazing_list
  password: <%= ENV["AMAZING_LIST_DATABASE_PASSWORD"] %>
